FROM balenalib/%%BALENA_MACHINE_NAME%%-python

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y bluez build-essential libglib2.0-dev

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python3", "./miflora-mqtt-daemon.py", "--config_dir", "/usr/src/app/config" ]
